# Copyright (c) 2023 Robert Bosch Manufacturing Solutions GmbH
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

enablePostgres: true

bpndiscovery:
  image:
    repository: basfatpdashboard.azurecr.io/sldt-bpn-discovery
    version: ""
    imagePullPolicy: IfNotPresent
  imagePullSecrets:
  - name: "atp-dashboard-image-pull-secret"
  replicaCount: 1
  containerPort: 4243
  host: bpn-discovery.dev.atp-dashboard.basf.com
  ## If 'authentication' is set to false, no OAuth authentication is enforced
  authentication: false
  idp:
    issuerUri: "https://centralidp.dev.atp-dashboard.basf.com/auth/realms/ATP-Central"
    publicClientId: bpn-discovery
    bpnIdClaimName: bpn
  ## Needed for the self-registration on discovery-finder
  bpndiscoveryEndpoint:
    allowedTypes: bpn
    description: "bpndiscovery"
    endpointAddress: "/bpndiscovery"
    documentation: "/swagger-ui/index.html"
  ## Configure discoveryFinderClient to register the bpn-discovery on discovery-finder.Properties needed for spring-security config.
  ## we are not using it currently
  discoveryfinderClient:
    baseUrl: "/discoveryfinder"
    registration:
      clientId: discovery-finder-client
      clientSecret: "client-secret"
      authorizationGrantType: client_credentials
    schedulerCronFrequency: "0 0 */1 * * *"
    provider:
      tokenUri: "/realms/discovery/protocol/openid-connect/token"
  service:
    port: 8080
    type: ClusterIP
  dataSource:
    driverClassName: org.postgresql.Driver
    sqlInitPlatform: pg
    ## The url, user, and password parameter will be ignored if 'enablePostgres' is set to true.
    ## In that case the postgresql auth parameters are used.
    url: jdbc:postgresql://database:5432
    user: user
    password: password
  ingress:
    enabled: false
    tls: false
    urlPrefix: /bpndiscovery
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
      nginx.ingress.kubernetes.io/x-forwarded-prefix: /bpndiscovery
  resources:
    limits:
      cpu: 750m
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 1024Mi

postgresql:
  primary:
    persistence:
      enabled: true
      size: 50Gi
  service:
    ports:
      postgresql: 5432
  auth:
    database: "<path:bpn_discovery/data/dev/database#name>"
    username: "<path:bpn_discovery/data/dev/database#user>"
    password: "<path:bpn_discovery/data/dev/database#password>"
## new added
vault:
  hashicorp:
    url: "https://vault.prod.atp-dashboard.basf.com"
    token: "<path:bpn_discovery/data/dev/vault#token>"
    timeout: 30
    healthCheck:
      enabled: true
      standbyOk: true
    paths:
      secret: /v1/secret
      health: /v1/sys/health
  secretNames:
    transferProxyTokenSignerPrivateKey:
    transferProxyTokenSignerPublicKey:
    transferProxyTokenEncryptionAesKey: transfer-proxy-token-encryption-aes-key
